[book]
authors = ["zhaosz"]
language = "en"
multilingual = false
src = "src"
title = "gc"

# https://doc.rust-lang.org/cargo/getting-started/installation.html
# cargo install mdbook
# cargo install mdbook-epub
[output.html]
